version: '3.8'

services:

  redis:
    image: redis:7.0.11-alpine
    container_name: redis-1

  django:
    container_name: django
    build:
      context: ./dcelery
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    volumes:
      - ./dcelery:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=fgkdfgl34jlk34n53
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery1:
    container_name: celery1
    build:
      context: ./dcelery
    command: celery --app=dcelery worker -l INFO -Q celery,celery:1,celery:2,celery:3
    volumes:
      - ./dcelery:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=fgkdfgl34jlk34n53
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django
  
  # celery2:
  #   container_name: celery2
  #   build:
  #     context: ./celeryworker
  #     dockerfile: Dockerfile
  #   command: celery -A celerytask worker -l INFO -Q queue2
  #   volumes:
  #     - ./celeryworker:/usr/src/app
  #   depends_on:
  #     - redis
  #     - django